create table awa_data(awaid int primary key auto_increment, queid int, username varchar(20), essay varchar(4000), email varchar(30),comments json,rating double);

INSERT INTO awa_data (`awaid`,`queid`,`username`,`essay`,`email`,`comments`,`rating`) VALUES (1,5,'Manan Dalal','hii this is manan\nthis is\nmy 1st essay','manandalal1012@gmail.com','[{\"value\": \"bohot ghatiya\", \"username\": \"Aman Dalal\"}, {\"value\": \"badhiya laga\", \"username\": \"Aman Dalal\"}, {\"value\": \"kya kuchbhi likhta hai\", \"username\": \"Aman Dalal\"}, {\"value\": \"last comment\", \"username\": \"Manan Dalal\"}]',3);
INSERT INTO awa_data (`awaid`,`queid`,`username`,`essay`,`email`,`comments`,`rating`) VALUES (2,6,'Manan Dalal','wg dyeguiewg yfgwyug gf gi eg\n wrg uirtr\nr rh ruir \nrtrjtritrr\nr tr jr iy riuu yruir turgutitr ur\n rturuithurtui rutrt \nrr tburthurhtuirhturt r rtr turhtu rtuiryruregtyufyrtr','manandalal1012@gmail.com','[{\"value\": \"worst\", \"username\": \"Honey Kapadia\"}, {\"value\": \"u can do better\", \"username\": \"Honey Kapadia\"}, {\"value\": \"bestttttttttttttttttt\", \"username\": \"Honey Kapadia\"}]',4.25);
INSERT INTO awa_data (`awaid`,`queid`,`username`,`essay`,`email`,`comments`,`rating`) VALUES (3,5,'Vasundhara U','testing','vasundhara.uchhula@gmail.com','[{\"value\": \"good\", \"username\": \"Manan Dalal\"}, {\"value\": \"i dont get this\", \"username\": \"Manan Dalal\"}, {\"value\": \"hehy\", \"username\": \"Manan Dalal\"}, {\"value\": \"\'last-comment\'\", \"username\": \"Manan Dalal\"}, {\"value\": \"hii\", \"username\": \"Manan Dalal\"}, {\"value\": \"Average\", \"username\": \"Manan Dalal\"}]',3.29);
INSERT INTO awa_data (`awaid`,`queid`,`username`,`essay`,`email`,`comments`,`rating`) VALUES (4,5,'Manan Dalal','after \'utf-8 convertor\'','manandalal1012@gmail.com',NULL,0);
INSERT INTO awa_data (`awaid`,`queid`,`username`,`essay`,`email`,`comments`,`rating`) VALUES (5,5,'Manan Dalal','Hii there','manandalal1012@gmail.com',NULL,0);
INSERT INTO awa_data (`awaid`,`queid`,`username`,`essay`,`email`,`comments`,`rating`) VALUES (6,1,'Mohit Mali','A society is a group of individuals involved in persistent social interaction, or a large social group sharing the same spatial or social territory, typically subject to the same political authority and dominant cultural expectations. Societies are characterized by patterns of relationships (social relations) between individuals who share a distinctive culture and institutions; a given society may be described as the sum total of such relationships among its constituent of members. In the social sciences, a larger society often exhibits stratification or dominance patterns in subgroups.\n\nSocieties construct patterns of behavior by deeming certain actions or speech as acceptable or unacceptable. These patterns of behavior within a given society are known as societal norms. Societies, and their norms, undergo gradual and perpetual changes.\n\nInsofar as it is collaborative, a society can enable its members to benefit in ways that would otherwise be difficult on an individual basis; both individual and social (common) benefits can thus be distinguished, or in many cases found to overlap. A society can also consist of like-minded people governed by their own norms and values within a dominant, larger society. This is sometimes referred to as a subculture, a term used extensively within criminology.','mohitmali3748@gmail.com','[{\"value\": \"this is first - \'comment\'\", \"username\": \"Jenish Modi\"}]',5);
INSERT INTO awa_data (`awaid`,`queid`,`username`,`essay`,`email`,`comments`,`rating`) VALUES (7,3,'Mohit Mali','maf,masvssvsvs jssv,svm ,ms,sms ,ms,s,,ms  ms,vsmvs,@@@@\n$$$C','mohitmali3748@gmail.com',NULL,0);
INSERT INTO awa_data (`awaid`,`queid`,`username`,`essay`,`email`,`comments`,`rating`) VALUES (8,2,'Megha Hogade','Argument is the term which is necessary to survive in this world..!!!!','meghahogade7@gmail.com','[{\"value\": \"very poor work need to work on it all the best next time\", \"username\": \"Mohit Mali\"}]',1);
INSERT INTO awa_data (`awaid`,`queid`,`username`,`essay`,`email`,`comments`,`rating`) VALUES (9,1,'Jenish Modi','[dscdsd]csdvv(csdcsd)<ddsc>sdc','jenishmodi556@gmail.com',NULL,0);
INSERT INTO awa_data (`awaid`,`queid`,`username`,`essay`,`email`,`comments`,`rating`) VALUES (10,4,'Manan Dalal','likhne pe maza isme toh','manandalal1012@gmail.com','[{\"value\": \"bohot ghatiya\", \"username\": \"Aman Dalal\"}, {\"value\": \"badhiya laga\", \"username\": \"Aman Dalal\"}, {\"value\": \"kya kuchbhi likhta hai\", \"username\": \"Aman Dalal\"}, {\"value\": \"last comment\", \"username\": \"Manan Dalal\"}]',3);
