create table words (id int primary key auto_increment, word varchar(20), opt json, ans varchar(30));

INSERT INTO words (`id`,`word`,`opt`,`ans`) VALUES (1,'Degrade','[\"descend\", \"humiliate\", \"inspect\", \"flatten\", \"upgrade\"]','humiliate');
INSERT INTO words (`id`,`word`,`opt`,`ans`) VALUES (2,'Resolve','[\"abondon\", \"determine\", \"declare innocent\", \"rewrite\", \"I\'m not sure\"]','determine');
INSERT INTO words (`id`,`word`,`opt`,`ans`) VALUES (3,'Belittle','[\"enrage\", \"shrink\", \"put somebody down\", \"reduce in physical size\", \"I\'m not sure\"]','put somebody down');
INSERT INTO words (`id`,`word`,`opt`,`ans`) VALUES (4,'Complimentary','[\"done\", \"flattering\", \"free\", \"matching\", \"I\'m not sure\"]','matching');
INSERT INTO words (`id`,`word`,`opt`,`ans`) VALUES (5,'Sentimental','[\"emotional\", \"lacking focus\", \"imprecise\", \"unstable\", \"I\'m not sure\"]','emotional');
INSERT INTO words (`id`,`word`,`opt`,`ans`) VALUES (6,'Pinnacle','[\"award\", \"front of a ship\", \"lucky charm\", \"highest point\", \"I\'m not sure\"]','highest point');
INSERT INTO words (`id`,`word`,`opt`,`ans`) VALUES (7,'Egotist','[\"boaster\", \"rebel\", \"philosopher\", \"manager\", \"I\'m not sure\"]','boaster');
INSERT INTO words (`id`,`word`,`opt`,`ans`) VALUES (8,'Cohesive','[\"united\", \"gullible\", \"tenacious\", \"filtered\", \"I\'m not sure\"]','united');
INSERT INTO words (`id`,`word`,`opt`,`ans`) VALUES (9,'Impartial','[\"guilty\", \"expressed in words\", \"unbiased\", \"part of a whole\", \"I\'m not sure\"]','unbiased');
INSERT INTO words (`id`,`word`,`opt`,`ans`) VALUES (10,'Serene','[\"sorrowful\", \"peaceful\", \"extremely hot\", \"disorganised\", \"I\'m not sure\"]','peaceful');
INSERT INTO words (`id`,`word`,`opt`,`ans`) VALUES (11,'Autonomous','[\"without a name\", \"independent\", \"productive\", \"uncaring\", \"I\'m not sure\"]','independent');
INSERT INTO words (`id`,`word`,`opt`,`ans`) VALUES (12,'Catalyst','[\"guarantee\", \"ancestor\", \"bright color\", \"cause of a process\", \"speedy\"]','cause of a process');
INSERT INTO words (`id`,`word`,`opt`,`ans`) VALUES (13,'Censor','[\"count\", \"remove objectionable material\", \"protect from danger\", \"disapprove of\", \"I\'m not sure\"]','remove objectionable material');
INSERT INTO words (`id`,`word`,`opt`,`ans`) VALUES (14,'Impermeable','[\"shameless\", \"slow-moving\", \"sealed\", \"momentary\", \"I\'m not sure\"]','sealed');
INSERT INTO words (`id`,`word`,`opt`,`ans`) VALUES (15,'Mesmerize','[\"bury\", \"remember\", \"separate\", \"hypnotize\", \"I\'m not sure\"]','hypnotize');
INSERT INTO words (`id`,`word`,`opt`,`ans`) VALUES (16,'Lethargic','[\"hostile\", \"weary\", \"sensitive\", \"incorrect\", \"I\'m not sure\"]','weary');
INSERT INTO words (`id`,`word`,`opt`,`ans`) VALUES (17,'Discriminate','[\"declare innocent\", \"accuse\", \"differentiate\", \"preserve\", \"I\'m not sure\"]','differentiate');
INSERT INTO words (`id`,`word`,`opt`,`ans`) VALUES (18,'Uncompromising','[\"inflexible\", \"angry\", \"shapeless\", \"without\", \"I\'m not sure\"]','inflexible');
INSERT INTO words (`id`,`word`,`opt`,`ans`) VALUES (19,'Economical','[\"rich\", \"common\", \"avoiding waste\", \"religious\", \"cheap\"]','avoiding waste');
INSERT INTO words (`id`,`word`,`opt`,`ans`) VALUES (20,'Irrefutable','[\"certain\", \"strange\", \"inferior\", \"blocked\", \"inspect\"]','certain');
INSERT INTO words (`id`,`word`,`opt`,`ans`) VALUES (21,'Laborious','[\"knowledgable\", \"radical\", \"demanding\", \"skilled\", \"I\'m not sure\"]','demanding');
INSERT INTO words (`id`,`word`,`opt`,`ans`) VALUES (22,'Elaborate','[\"detailed\", \"infected\", \"internal\", \"struggling\", \"I\'m not sure\"]','detailed');
INSERT INTO words (`id`,`word`,`opt`,`ans`) VALUES (23,'Anomaly','[\"oddity\", \"agreement\", \"retirement\", \"forgetfulness\", \"I\'m not sure\"]','oddity');
INSERT INTO words (`id`,`word`,`opt`,`ans`) VALUES (24,'Constraint','[\"limit\", \"tightness\", \"anxiety\", \"defense\", \"I\'m not sure\"]','limit');
INSERT INTO words (`id`,`word`,`opt`,`ans`) VALUES (25,'Analogous','[\"transforming\", \"physical\", \"similar\", \"irrational\", \"I\'m not sure\"]','similar');
INSERT INTO words (`id`,`word`,`opt`,`ans`) VALUES (26,'Appropriate','[\"take forcefully\", \"make usable\", \"make known\", \"open\", \"I\'m not sure\"]','take forcefully');
INSERT INTO words (`id`,`word`,`opt`,`ans`) VALUES (27,'bleak','[\"aggressive\", \"average\", \"hopeless\", \"promising\", \"I\'m not sure\"]','hopeless');
INSERT INTO words (`id`,`word`,`opt`,`ans`) VALUES (28,'decry','[\"express sadness\", \"delay\", \"speak out against\", \"refer to\", \"I\'m not sure\"]','speak out against');
INSERT INTO words (`id`,`word`,`opt`,`ans`) VALUES (29,'profuse','[\"abundant\", \"confident\", \"short-tempered\", \"large\", \"I\'m not sure\"]','abundant');
INSERT INTO words (`id`,`word`,`opt`,`ans`) VALUES (30,'contentious','[\"without planning\", \"competitive\", \"causing arguments\", \"satisfied\", \"I\'m not sure\"]','causing arguments');
INSERT INTO words (`id`,`word`,`opt`,`ans`) VALUES (31,'modicum','[\"an average size\", \"playful behavior\", \"dishonesty\", \"a small amount\", \"I\'m not sure\"]','a small amount');
INSERT INTO words (`id`,`word`,`opt`,`ans`) VALUES (32,'meander','[\"set in motion\", \"speak unclearly\", \"long for\", \"wander\", \"I\'m not sure\"]','wander');
INSERT INTO words (`id`,`word`,`opt`,`ans`) VALUES (33,'pastoral','[\"bygone\", \"wealthy\", \"rural\", \"hidden\", \"I\'m not sure\"]','rural');
INSERT INTO words (`id`,`word`,`opt`,`ans`) VALUES (34,'obscure','[\"unique\", \"argue\", \"make untidy\", \"hide from view\", \"I\'m not sure\"]','hide from view');
INSERT INTO words (`id`,`word`,`opt`,`ans`) VALUES (35,'maverick','[\"conformist\", \"unwanted person\", \"radical thinker\", \"warrior\", \"I\'m not sure\"]','radical thinker');
INSERT INTO words (`id`,`word`,`opt`,`ans`) VALUES (36,'tyro','[\"liar\", \"dictator\", \"businessman\", \"beginner\", \"I\'m not sure\"]','beginner');
INSERT INTO words (`id`,`word`,`opt`,`ans`) VALUES (37,'inequity','[\"unfairness\", \"foolishness\", \"wealth of ideas\", \"lack of resources\", \"I\'m not sure\"]','unfairness');
INSERT INTO words (`id`,`word`,`opt`,`ans`) VALUES (38,'despot','[\"source\", \"fraud\", \"tyrant\", \"enemy\", \"I\'m not sure\"]','tyrant');
INSERT INTO words (`id`,`word`,`opt`,`ans`) VALUES (39,'loath','[\"hate-filled\", \"call out\", \"unnecessary\", \"reluctant\", \"I\'m not sure\"]','reluctant');
INSERT INTO words (`id`,`word`,`opt`,`ans`) VALUES (40,'morose','[\"scholarly\", \"gloomy\", \"plentiful\", \"righteous\", \"I\'m not sure\"]','gloomy');
INSERT INTO words (`id`,`word`,`opt`,`ans`) VALUES (41,'proponent','[\"adviser\", \"supporter\", \"specialist\", \"energy booster\", \"I\'m not sure\"]','supporter');
INSERT INTO words (`id`,`word`,`opt`,`ans`) VALUES (42,'obstinate','[\"ignorant\", \"agreeable\", \"stubborn\", \"uninformed\", \"I\'m not sure\"]','stubborn');
INSERT INTO words (`id`,`word`,`opt`,`ans`) VALUES (43,'puerile','[\"experienced\", \"happy\", \"childish\", \"uncorrupted\", \"I\'m not sure\"]','childish');
INSERT INTO words (`id`,`word`,`opt`,`ans`) VALUES (44,'myriad','[\"favourable event\", \"large number\", \"unwritten rule\", \"secret location\", \"I\'m not sure\"]','large number');
INSERT INTO words (`id`,`word`,`opt`,`ans`) VALUES (45,'expunge','[\"erase\", \"conceal\", \"attack\", \"substitute\", \"I\'m not sure\"]','erase');
INSERT INTO words (`id`,`word`,`opt`,`ans`) VALUES (46,'conductive','[\"lacking\", \"helpful\", \"joyful\", \"hostile\", \"I\'m not sure\"]','helpful');
INSERT INTO words (`id`,`word`,`opt`,`ans`) VALUES (47,'evanescent','[\"exited\", \"short-lived\", \"powerful\", \"creative\", \"I\'m not sure\"]','short-lived');
INSERT INTO words (`id`,`word`,`opt`,`ans`) VALUES (48,'desecrate','[\"ruin something holy\", \"dry up\", \"consider worthless\", \"deserve\", \"I\'m not sure\"]','ruin something holy');
INSERT INTO words (`id`,`word`,`opt`,`ans`) VALUES (49,'inviolable','[\"well-liked\", \"sacred\", \"peaceful\", \"forgotten\", \"I\'m not sure\"]','sacred');
INSERT INTO words (`id`,`word`,`opt`,`ans`) VALUES (50,'complaisant','[\"self-satisfied\", \"stubborn\", \"cheerfully obedient\", \"bossy\", \"I\'m not sure\"]','cheerfully obedient');

